version: '3.8'
services:
  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_HOSTS=%
      - MYSQL_DATABASE=dechorizon
      - MYSQL_ALLOW_EMPTY_PASSWORD=1
    volumes:
      - ./docker/volume_mysql:/var/lib/mysql
